fix: Fix ingest script

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -34,10 +34,12 @@ jobs:
 
       - name: Test that flask starts
         run: |-
+          # This tests that we fail when the server is down
+          python ingest.py; [[ "$?" == 1 ]]
           # This saves the initial checkout of the repos and let's the Flask app initialize quickly
           export FAST_STARTUP=1
           nohup flask run &
-          sleep 3 && curl --request POST http://0.0.0.0:5000
+          sleep 3 && python ingest.py
 
   tests:
     name: unit tests
